_base_ = [
    '../carla/carlasim_map.py',
]
#
# MapTRv2 LiDAR-only config (CARLA) -- 30m x 30m tiles (tile_radius=15).
#
# Sibling of maptrv2_carla_r50_24ep_lidar.py, which targets the original
# 25m x 25m export (tile_radius=12.5). Everything that is NOT tile-size
# dependent is deliberately identical to that file, so a diff between the
# two shows exactly what tile size costs. The tile-size dependent knobs are
# marked "[30m]" below; there are seven of them, and one (data.*.pc_range)
# is NOT overridden by the 25m config and therefore easy to miss -- see the
# note on it further down.
#
# Requires a 30m pkl generated by the (now tile-size agnostic) converter:
#   python tools/maptrv2/custom_carla_map_converter.py \
#       --data-root <30m export> --out-dir data/carla_30m/ --split test
# The converter derives --lidar-point-cloud-range from the manifest's own
# tile_radius/tile_side, so it will pick +-15 by itself; the range recorded
# in the pkl must match lidar_point_cloud_range below or the dataset warns.
#
plugin = True
plugin_dir = 'projects/mmdet3d_plugin/'

# [30m] Matches the 30m x 30m square CARLA tile (tile_radius=15). z-range is
# generous: divider polylines are XY-only for code_size=2 (z gets clamped
# but never reaches the final regression target), and this just needs to
# comfortably contain the LiDAR point cloud's z spread. z is unchanged from
# the 25m config -- tile size is an XY property.
point_cloud_range = [-15.0, -15.0, -30.0, 15.0, 15.0, 20.0]
# Deliberately NOT scaled with tile size: MapTRNMSFreeCoder stores
# voxel_size and never reads it (nms_free_coder.py:92), as does
# train_cfg.pts. Left identical to the 25m config so a diff between the two
# stays honest about what actually changed.
voxel_size = [0.15, 0.15, 20.0]

# [30m] LiDAR branch geometry (kept separate from the map/coder
# point_cloud_range above -- same 30m x/y extent). The z range is unchanged
# from the 25m config and is not a tile-size property: it exists to cover 6
# confirmed town03 tiles whose LiDAR returns span z in [-66.90, 90.52]
# within a single tile (a highway overpass, not flat driving surface). See
# the 25m config for the full history. z_max in carlasim_map.py
# (LoadCarlaPointsFromFile's early filter) must stay >= this range's z upper
# bound.
#
# NOTE (CLAUDE.md open item): 98 tiles in the 25m train set have z_min below
# -72, reaching -97.1. That is a pre-existing issue inherited here, not
# something 30m tiles introduce -- if the range is widened, re-measure
# sparse_shape below.
lidar_point_cloud_range = [-15.0, -15.0, -72.0, 15.0, 15.0, 96.0]
# Unchanged: this is a resolution, not an extent. Holding it fixed is what
# makes the 30m grid bigger (300 x/y cells instead of 250) rather than
# coarser.
lidar_voxel_size = [0.1, 0.1, 0.4]

map_classes = ['divider']
num_vec=50
fixed_ptsnum_per_gt_line = 20 # now only support fixed_pts > 0
fixed_ptsnum_per_pred_line = 20
eval_use_same_gt_sample_num_flag=True
num_map_classes = len(map_classes)

# [30m] The 30m export needs its own pkl, and -- critically -- its own
# map_ann_file. carlasim_map.py points map_ann_file at
# data/carla/carla_map_gt.json, and _format_gt() SKIPS regeneration whenever
# that file already exists (CLAUDE.md). Inheriting it would make a 30m eval
# silently score against the 25m ground truth. Overridden in data.val/test
# below, not just here.
data_root = 'data/carla_30m/'
ann_file_train = data_root + 'carla_map_infos_train.pkl'
ann_file_val = data_root + 'carla_map_infos_test.pkl'
ann_file_test = data_root + 'carla_map_infos_test.pkl'
map_ann_file = data_root + 'carla_map_gt.json'

# [30m] The dataset's own pc_range, which is NOT the same list as the model's
# point_cloud_range above: carlasim_map.py uses z [-2, 24] here while the
# model uses [-30, 20]. Only xy is widened to +-15; the z bounds are left at
# the 25m config's effective values so a diff between the two configs shows
# tile size and nothing else. The dataset uses this z solely to clamp GT
# polyline z (av2_offlinemap_dataset.py), which never reaches the regression
# target at code_size=2 -- so it is inert here either way.
dataset_pc_range = [-15.0, -15.0, -2.0, 15.0, 15.0, 24.0]

input_modality = dict(
    use_lidar=True,
    use_camera=False,
    use_radar=False,
    use_map=False,
    use_external=False)

_dim_ = 256
_pos_dim_ = _dim_//2
_ffn_dim_ = _dim_*2
_num_levels_ = 1
# [30m] Square, matching the square 30m x 30m point_cloud_range above
# (gotcha #8: this must match the range's aspect ratio AND be passed to the
# dataset as bev_size, which it is, below).
#
# 120 rather than the 25m config's 100 keeps the BEV cell size at 0.25 m
# (30/120), identical to that config's 25/100. Holding bev_h_=100 here
# would also be valid -- square is square -- but would coarsen cells to
# 0.30 m against chamfer thresholds of 0.5/1.0/1.5 m. The cost is 1.44x the
# BEV tokens (14400 vs 10000) feeding the decoder's cross-attention, so if
# this OOMs on a 20GB MIG partition before samples_per_gpu can be raised,
# dropping to 100 is the first thing to try -- it is a pure resolution knob
# and nothing else in this file depends on it.
bev_h_ = 120
bev_w_ = 120
queue_length = 1 # each sequence contains `queue_length` frames.

aux_seg_cfg = dict(
    use_aux_seg=True,
    bev_seg=True,
    pv_seg=False,  # no camera imagery to rasterize into
    seg_classes=1,
    feat_down_sample=32,
    pv_thickness=1,
)

model = dict(
    type='MapTRv2',
    use_grid_mask=True,
    video_test_mode=False,
    modality='lidar',
    lidar_encoder=dict(
        voxelize=dict(
            max_num_points=10,
            point_cloud_range=lidar_point_cloud_range,
            voxel_size=lidar_voxel_size,
            max_voxels=[90000, 120000]),
        backbone=dict(
            type='SparseEncoder',
            in_channels=4,  # CARLA points are xyz + strength (not nuScenes' xyz+intensity+ring=5)
            # [30m] (x, y, z) order -- gotcha #4; do NOT trust SparseEncoder's
            # own docstring, which claims (z, y, x).
            #
            # x/y: 30m / 0.1m = 300 cells -> 301. The 25m config's 251 is the
            # same +1 convention on 250. z: unchanged from the 25m config
            # (168m / 0.4m = 420 -> 421), since the z range and z voxel size
            # are both unchanged.
            #
            # Verified empirically against this exact config via a dummy
            # extract_lidar_feat() call rather than hand-derived, per
            # CLAUDE.md -- see the "verified" note on lidar_bev_proj below.
            sparse_shape=[301, 301, 421],
            output_channels=128,
            order=('conv', 'norm', 'act'),
            encoder_channels=((16, 16, 32), (32, 32, 64), (64, 64, 128), (128,
                                                                          128)),
            encoder_paddings=([0, 0, 1], [0, 0, 1], [0, 0, [1, 1, 0]], [0, 0]),
            block_type='basicblock'
        ),
    ),
    pts_bbox_head=dict(
        type='MapTRv2Head',
        bev_h=bev_h_,
        bev_w=bev_w_,
        num_query=900,
        num_vec_one2one=50,
        num_vec_one2many=300,
        k_one2many=6,
        num_pts_per_vec=fixed_ptsnum_per_pred_line, # one bbox
        num_pts_per_gt_vec=fixed_ptsnum_per_gt_line,
        dir_interval=1,
        query_embed_type='instance_pts',
        transform_method='minmax',
        gt_shift_pts_pattern='v2',
        num_classes=num_map_classes,
        in_channels=_dim_,
        sync_cls_avg_factor=True,
        with_box_refine=True,
        as_two_stage=False,
        code_size=2,
        code_weights=[1.0, 1.0, 1.0, 1.0],
        aux_seg=aux_seg_cfg,
        transformer=dict(
            type='MapTRPerceptionTransformer',
            rotate_prev_bev=True,
            use_shift=True,
            use_can_bus=True,
            embed_dims=_dim_,
            modality='lidar',
            # SparseEncoder outputs C*D channels (output_channels=128 * the
            # z-dim after its internal downsampling).
            #
            # UNCHANGED from the 25m config at 3200, and that is the whole
            # point of measuring rather than scaling: this number depends
            # only on z (128 * 25), and z geometry is identical here. The
            # x/y growth shows up purely as a larger spatial feature map
            # (38x38 here vs 32x32 at 25m), which never reaches this
            # channel count -- transformer.py bicubic-interpolates the
            # LiDAR feature to (bev_h, bev_w) before lidar_bev_proj sees it
            # (transformer.py:267), so bev_h_/bev_w_ above are free
            # parameters rather than being pinned to the encoder's output.
            #
            # Verified empirically against this exact config via a dummy
            # extract_lidar_feat() call: output shape (1, 3200, 38, 38).
            lidar_bev_proj=dict(
                type='ConvFuser',
                in_channels=[3200],
                out_channels=_dim_,
            ),
            # Structurally required by MapTRPerceptionTransformer.__init__
            # (build_transformer_layer_sequence(encoder) always runs) but
            # never invoked on the modality='lidar' path -- kept minimal.
            encoder=dict(
                type='BEVFormerEncoder',
                num_layers=1,
                pc_range=point_cloud_range,
                num_points_in_pillar=4,
                return_intermediate=False,
                transformerlayers=dict(
                    type='BEVFormerLayer',
                    attn_cfgs=[
                        dict(
                            type='TemporalSelfAttention',
                            embed_dims=_dim_,
                            num_levels=1),
                        dict(
                            type='GeometrySptialCrossAttention',
                            pc_range=point_cloud_range,
                            attention=dict(
                                type='GeometryKernelAttention',
                                embed_dims=_dim_,
                                num_heads=4,
                                dilation=1,
                                kernel_size=(3,5),
                                num_levels=_num_levels_),
                            embed_dims=_dim_,
                        )
                    ],
                    feedforward_channels=_ffn_dim_,
                    ffn_dropout=0.1,
                    operation_order=('self_attn', 'norm', 'cross_attn', 'norm',
                                     'ffn', 'norm'))),
            decoder=dict(
                type='MapTRDecoder',
                num_layers=6,
                return_intermediate=True,
                transformerlayers=dict(
                    type='DecoupledDetrTransformerDecoderLayer',
                    num_vec=num_vec,
                    num_pts_per_vec=fixed_ptsnum_per_pred_line,
                    attn_cfgs=[
                        dict(
                            type='MultiheadAttention',
                            embed_dims=_dim_,
                            num_heads=8,
                            dropout=0.1),
                        dict(
                            type='MultiheadAttention',
                            embed_dims=_dim_,
                            num_heads=8,
                            dropout=0.1),
                         dict(
                            type='CustomMSDeformableAttention',
                            embed_dims=_dim_,
                            num_levels=1),
                    ],

                    feedforward_channels=_ffn_dim_,
                    ffn_dropout=0.1,
                    operation_order=('self_attn', 'norm', 'self_attn', 'norm','cross_attn', 'norm',
                                     'ffn', 'norm')))),
        bbox_coder=dict(
            type='MapTRNMSFreeCoder',
            # [30m] pc_range's xy extent plus the same 2m margin the 25m
            # config uses (12.5 -> 14.5 becomes 15.0 -> 17.0).
            post_center_range=[-17.0, -17.0, -17.0, -17.0, 17.0, 17.0, 17.0, 17.0],
            pc_range=point_cloud_range,
            max_num=50,
            voxel_size=voxel_size,
            num_classes=num_map_classes),
        positional_encoding=dict(
            type='LearnedPositionalEncoding',
            num_feats=_pos_dim_,
            row_num_embed=bev_h_,
            col_num_embed=bev_w_,
            ),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=2.0),
        loss_bbox=dict(type='L1Loss', loss_weight=0.0),
        loss_iou=dict(type='GIoULoss', loss_weight=0.0),
        loss_pts=dict(type='PtsL1Loss',
                      loss_weight=5.0),
        loss_dir=dict(type='PtsDirCosLoss', loss_weight=0.005),
        loss_seg=dict(type='SimpleLoss',
            pos_weight=4.0,
            loss_weight=1.0),
        loss_pv_seg=dict(type='SimpleLoss',
                    pos_weight=1.0,
                    loss_weight=2.0),),
    # model training and testing settings
    train_cfg=dict(pts=dict(
        grid_size=[512, 512, 1],
        voxel_size=voxel_size,
        point_cloud_range=point_cloud_range,
        out_size_factor=4,
        assigner=dict(
            type='MapTRAssigner',
            cls_cost=dict(type='FocalLossCost', weight=2.0),
            reg_cost=dict(type='BBoxL1Cost', weight=0.0, box_format='xywh'),
            iou_cost=dict(type='IoUCost', iou_mode='giou', weight=0.0),
            pts_cost=dict(type='OrderedPtsL1Cost',
                      weight=5),
            pc_range=point_cloud_range))))

file_client_args = dict(backend='disk')

# GridSamplePoints must live here (not in carlasim_map.py's base
# train_pipeline/test_pipeline) because it needs lidar_point_cloud_range,
# which only exists in this derived config -- mmcv's per-file config
# isolation means the base file can't see it. Collapses each tile's raw
# LiDAR points to ~1 representative point per occupied
# (lidar_voxel_size)-sized cell before the (slow, and at extreme point
# counts, silently incorrect -- see CLAUDE.md) LiDAR voxelizer ever sees
# them. grid_size matches lidar_voxel_size exactly so this adds no
# spatial precision loss beyond what the voxelizer already imposes.
train_pipeline = [
    dict(
        type='LoadCarlaPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        z_max=96.0),
    dict(
        type='GridSamplePoints',
        grid_size=lidar_voxel_size,
        point_cloud_range=lidar_point_cloud_range),
    dict(
        type='DefaultFormatBundle3D',
        with_gt=False,
        with_label=False,
        class_names=map_classes),
    dict(type='CustomCollect3D', keys=['points'])
]

# Matches carlasim_map.py's own test_pipeline shape (inherited at the
# data.test dict level via _base_), plus the same GridSamplePoints step as
# train_pipeline above; redefined here as a bare name partly because
# `evaluation` below needs it directly and _base_ variables aren't visible
# as plain Python names in this file's own execution scope.
test_pipeline = [
    dict(
        type='LoadCarlaPointsFromFile',
        coord_type='LIDAR',
        load_dim=4,
        use_dim=4,
        # Kept in sync with carlasim_map.py's own z_max and this file's
        # lidar_point_cloud_range z upper bound -- see the comments there.
        z_max=96.0),
    dict(
        type='GridSamplePoints',
        grid_size=lidar_voxel_size,
        point_cloud_range=lidar_point_cloud_range),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1, 1),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(
                type='DefaultFormatBundle3D',
                with_gt=False,
                with_label=False,
                class_names=map_classes),
            dict(type='CustomCollect3D', keys=['points'])
        ])
]

# carlasim_map.py's dataset dicts don't set these (they're model-config
# concerns, matching the nuScenes/AV2 convention of overriding them here).
#
# min_lidar_points/lidar_pc_range drop tiles whose LiDAR points all fall
# outside lidar_point_cloud_range -- those voxelize to zero voxels and crash
# extract_lidar_feat. The converter already drops them when generating the
# pkl (and records the per-tile in-range count each sample carries); these
# make the dataset re-check, and warn if the pkl was generated against a
# different range than the one this config uses.
#
# [30m] pc_range/data_root/ann_file/map_ann_file are overridden here and are
# the easiest thing to get wrong when deriving a new tile size, because the
# 25m config does NOT override them -- it silently inherits carlasim_map.py's
# 25m values, which happen to be correct for it. They are not correct here:
#   * pc_range sets the dataset's map patch size directly
#     (carla_offlinemap_dataset.py:77-78 -> patch_h/patch_w), so leaving it
#     at +-12.5 would crop 30m GT into a 25m patch while the model regressed
#     against +-15 -- a silent frame mismatch of exactly the kind that cost
#     ~2.4m of GT displacement before commit aaf4b46. Only the xy bounds
#     change; the z bounds keep carlasim_map.py's [-2, 24] dataset
#     convention, which is separate from the model's [-30, 20] above.
#   * map_ann_file must differ from the 25m one or _format_gt() reuses the
#     cached 25m GT (it skips regeneration when the file exists).
data = dict(
    train=dict(
        data_root=data_root,
        ann_file=ann_file_train,
        pc_range=dataset_pc_range,
        pipeline=train_pipeline,
        fixed_ptsnum_per_line=fixed_ptsnum_per_gt_line,
        eval_use_same_gt_sample_num_flag=eval_use_same_gt_sample_num_flag,
        bev_size=(bev_h_, bev_w_),
        min_lidar_points=1,
        lidar_pc_range=lidar_point_cloud_range,
        # Needed so the dataset's own vector_map produces gt_seg_mask,
        # matching aux_seg_cfg's use_aux_seg/bev_seg above (only wired for
        # train -- bev_seg is a training-time auxiliary loss).
        aux_seg=aux_seg_cfg),
    val=dict(
        data_root=data_root,
        ann_file=ann_file_val,
        map_ann_file=map_ann_file,
        pc_range=dataset_pc_range,
        pipeline=test_pipeline,
        fixed_ptsnum_per_line=fixed_ptsnum_per_gt_line,
        eval_use_same_gt_sample_num_flag=eval_use_same_gt_sample_num_flag,
        bev_size=(bev_h_, bev_w_),
        min_lidar_points=1,
        lidar_pc_range=lidar_point_cloud_range),
    test=dict(
        data_root=data_root,
        ann_file=ann_file_test,
        map_ann_file=map_ann_file,
        pc_range=dataset_pc_range,
        pipeline=test_pipeline,
        fixed_ptsnum_per_line=fixed_ptsnum_per_gt_line,
        eval_use_same_gt_sample_num_flag=eval_use_same_gt_sample_num_flag,
        bev_size=(bev_h_, bev_w_),
        min_lidar_points=1,
        lidar_pc_range=lidar_point_cloud_range),
    shuffler_sampler=dict(type='DistributedGroupSampler'),
    nonshuffler_sampler=dict(type='DistributedSampler'),
)

optimizer = dict(
    type='AdamW',
    lr=6e-4,
    weight_decay=0.01)

optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='CosineAnnealing',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    min_lr_ratio=1e-3)
total_epochs = 24
evaluation = dict(interval=2, pipeline=test_pipeline, metric='chamfer',
                  save_best='CarlaMap_chamfer/mAP', rule='greater')

runner = dict(type='EpochBasedRunner', max_epochs=total_epochs)

log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
fp16 = dict(loss_scale=512.)
checkpoint_config = dict(max_keep_ckpts=1, interval=2)
find_unused_parameters=True
