"""R1: double the LiDAR BEV resolution, on top of ablation winner C (lr 3e-4).

Measured motivation:
  * C's remaining gap is entirely divider localisation: AP@0.5 0.7424 vs
    AP@1.5 0.8861 (curb's gap is only 0.0329), recall@0.5 0.6698.
  * SparseEncoder emits 38x38 for the 30 m crop = 0.789 m/cell, and
    transformer.get_bev_features BICUBICALLY UPSAMPLES that to bev_h/bev_w.
    So bev_h=120 carries no information beyond the 38x38 -- raising bev_h
    alone would do nothing. The real knob is the voxel size.
  * v=0.05 -> sparse_shape 601 -> 76x76 = 0.395 m/cell (measured, not derived).
  * 0.05 m voxels give 112k voxels/crop (median), so max_voxels must rise from
    90k/120k. At 0.10 the median was already 74.8k against a 90k cap, i.e. the
    baseline was occasionally truncating too.
"""
from mmcv import Config
import sys
V=float(sys.argv[1]) if len(sys.argv)>1 else 0.05
NAME=sys.argv[2] if len(sys.argv)>2 else 'R1_hires'
SS=int(round(30.0/V))+1
MV=int(sys.argv[3]) if len(sys.argv)>3 else 160000
SRC='/MapTR2/projects/configs/maptrv2/abl_C_lr05x.py'
OUT=f'/MapTR2/projects/configs/maptrv2/abl_{NAME}.py'
cfg=Config.fromfile(SRC)
le=cfg.model['lidar_encoder']
le['voxelize']['voxel_size']=[V,V,0.4]
le['voxelize']['max_voxels']=[MV,int(MV*1.25)]
le['backbone']['sparse_shape']=[SS,SS,421]
# every reported run used 16; the inherited 22 OOMs on 50 m crops
# (68 GB of 81). Pin it so the config reproduces without cfg-options.
cfg.data['samples_per_gpu']=16
# top-level `voxel_size` is the HEAD's grid (0.15/20.0), not the voxelizer's;
# leave it alone. `lidar_voxel_size` is the one that should track the change.
cfg._cfg_dict['lidar_voxel_size']=[V,V,0.4]
open(OUT,'w').write('# R1 = ablation winner C (lr 3e-4) + 2x LiDAR BEV resolution.\n'
                    '# Generated by tools/carla50m/make_hires.py -- edit that, not this.\n'
                    +cfg.pretty_text)
print('wrote',OUT)
print('  voxel_size  ', le['voxelize']['voxel_size'])
print('  sparse_shape', le['backbone']['sparse_shape'])
print('  max_voxels  ', le['voxelize']['max_voxels'])
print('  lr          ', cfg.optimizer['lr'])
